# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095709cf33dd11f967b42e15bf3052c075d948e9d353d325fcd0616374ce7961a7a7a490bb2de482e69a768d602e6d0fc3a5bf34c1ca5a05bda04816755bc246

test:
  secret_key_base: 3c08550cc270d367463bc12268b469dc0b43c835ae04e9bdb901f56f4797278be8e33191c30a7924b89c2ec7546757cc605a721e4fa4631b97ad645d821fa2a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
